type = "card"
title = "荣誉奖项"
description = "所获荣誉与奖项。"

[[items]]
title = "中国移动第四届"梧桐杯"人工智能赛道"
subtitle = "中国移动"
date = "2025.04"
content = "全国亚军"

[[items]]
title = "美国大学生数学建模竞赛 (MCM/ICM)"
subtitle = "COMAP"
date = "2025.05"
content = "M 奖"

[[items]]
title = "大学生创新创业训练计划年会"
subtitle = "哈尔滨工业大学"
date = "2024.11"
content = "本科负责人"

[[items]]
title = "生命医学工程竞赛"
subtitle = "全国"
date = "2025.07"
content = "国家级一等奖"

[[items]]
title = "全国大学生生命科学竞赛"
subtitle = "全国"
date = "2025.07"
content = "国家级二等奖"

[[items]]
title = "高教杯全国大学生数学建模竞赛"
subtitle = "教育部"
date = "2024.12"
content = "省级一等奖"

[[items]]
title = "全国大学生创新创业产业赛道"
subtitle = "全国"
date = "2024.10"
content = "银奖"

[[items]]
title = "全国职业规划大赛"
subtitle = "黑龙江省"
date = "2025.05"
content = "黑龙江省冠军"
