[[news]]
date = "2026-04"
content = "论文 PresCast 被 **NeurIPS 2026** 接收 🎉"

[[news]]
date = "2026-04"
content = "论文 MelTrim 被 **ACL Findings 2026** 接收 🎉"

[[news]]
date = "2025-11"
content = "论文 ImageBindDC 被 **AAAI 2026** 接收 🎉"

[[news]]
date = "2025-07"
content = "生命医学工程竞赛获国家级一等奖，全国大学生生命科学竞赛获国家级二等奖"

[[news]]
date = "2025-05"
content = "MCM/ICM 美国大学生数学建模竞赛获 M 奖"

[[news]]
date = "2025-04"
content = "梧桐杯 AI 赛道获全国亚军"
